{% set name = "mapbox_earcut" %}
{% set version = "2.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fb0c1e43581a635bbaabf4a5149009014d370c515816c4d5a7d8118477f28d48
  patches:
    - patches/skip-stub-generation-when-cross-compiling.patch

build:
  number: 1
  script: "{{ PYTHON }} -m pip install -vv ."
  skip: true  # [python_impl == 'pypy' or py<39]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11                               # [build_platform != target_platform]
    - scikit-build-core                      # [build_platform != target_platform]
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - make
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - numpy  # [build_platform != target_platform]
  host:
    - python
    - numpy
    - pip
    - pybind11
    - scikit-build-core
    - nanobind
  run:
    - python
    - {{ pin_compatible('libgd') }}

test:
  requires:
    - pytest

  imports:
    - mapbox_earcut

  files:
    - test_earcut.py

  commands:
    - pytest test_earcut.py

about:
  home: https://github.com/skogler/mapbox_earcut_python
  license: "ISC AND BSD-3-Clause"
  license_file:
    - LICENSE.md
    - include/mapbox/LICENSE
  summary: "Python version of Mapbox Earcut library: fast and quite robust triangulation of 2D polygons."
  description: |
    The library implements a modified ear slicing algorithm, optimized by z-order
    curve hashing and extended to handle holes, twisted polygons, degeneracies and
    self-intersections in a way that doesn't guarantee correctness of triangulation,
    but attempts to always produce acceptable results for practical data like
    geographical shapes.
  dev_url: https://github.com/skogler/mapbox_earcut_python

extra:
  recipe-maintainers:
    - pb01ka
    - ChrisBarker-NOAA
    - jay-hennen
    - JamesMakela-NOAA
